### ISSUE TITLE
Unable to discover the device

### ISSUE THREAD

**Issue by bugavka** [volshebniks/xiaomi_mijia_ptx#2]
Здравствуйте, 
где-то с неделю отвалился выключатель от HAS.
в логах 
2021-10-10 14:01:53 ERROR (MainThread) [custom_components.xiaomi_mijia_ptx.switch] Got exception while fetching the state: Unable to discover the device 192.168.10.244

HAS установлен в режиме Core.

Версия | core-2021.8.6
Тип установки | Home Assistant Core
Среда разработки | false
Supervisor | false
Docker | false
user | homeassistant
Виртуальное окружение | true
Версия Python | 3.8.10
Семейство операционных систем | Linux
Версия операционной системы | 5.4.0-88-generic
Архитектура ЦП | x86_64

Устройство с сервера пингуется. Через приложение Михом работает.
Ошибка с моей стороны?

**Comment by volshebniks** [comment]
к сожалению - у меня еще как минимум месяц,  нет возможности проверить. так как больше нет таких выключателей.

**Comment by bugavka** [comment]
Не актуально, ошибка не в интеграции
