### ISSUE TITLE
cannot import name 'SwitchDevice'

### ISSUE THREAD

**Issue by ghost** [volshebniks/xiaomi_mijia_ptx#4]
调用服务 homeassistant/restart 失败。 The system cannot restart because the configuration is not valid: Platform error switch.xiaomi_mijia_ptx - cannot import name 'SwitchDevice' from 'homeassistant.components.switch' (/usr/src/homeassistant/homeassistant/components/switch/__init__.py)

2022-8-3安装的HA 和 HACS最新版报上面错误
然后装2022-2月份的HA 和 HACS均报上面错误

MODEL:    090615.switch.xswitch03
请帮忙解决！谢谢！

**Comment by volshebniks** [comment]
remove unusable SwitchDevice import in 0.4.1
